# Generated by Django 5.2.2 on 2025-06-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='captions',
            field=models.TextField(),
        ),
    ]
