# Generated by Django 5.2.2 on 2025-06-07 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_likepost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profileImg',
            new_name='profileimg',
        ),
    ]
